export const lands = [
  {
    war_id: 0,
    id: 1,
    clan: 1,
    attackersPower: 44,
    defendersPower: 47,
    value: 5,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['mustocode', 14, '0x000f'],
      ['batucode', 15, '0x000f'],
      ['mertcode', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['ensar', 7, '0x000f'],
      ['taygun', 15, '0x000f'],
      ['ozge', 25, '0x000f'],
    ],
    road: [],
    city_name: 'Hayato',
    desc: 'Bu savaş Hayato şehrinde gerçekleşiyor ve iki klan arasındaki güç dengesi oldukça yakın.',
  },
  {
    war_id: 0,
    id: 2,
    clan: 0,
    attackersPower: 48,
    defendersPower: 50,
    value: 7,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['mustafa', 16, '0x000f'],
      ['batuhan', 19, '0x000f'],
      ['mehmet', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['aylin', 10, '0x000f'],
      ['tuna', 16, '0x000f'],
      ['berk', 24, '0x000f'],
    ],
    road: [1, 3, 4, 5],
    city_name: 'Kagutsuchi',
    desc: 'Kagutsuchi şehri, kutsal bir volkanın eteklerinde yer alıyor ve bu savaşta iki klan arasında oldukça yüksek bir meblağ bahis oynanıyor.',
  },
  {
    war_id: 0,
    id: 3,
    clan: 0,
    attackersPower: 35,
    defendersPower: 60,
    value: 10,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['hikaru', 11, '0x000f'],
      ['ryota', 14, '0x000f'],
      ['takumi', 20, '0x000f'],
    ],
    defenderSamurai: [
      ['mika', 16, '0x000f'],
      ['shin', 16, '0x000f'],
      ['aya', 28, '0x000f'],
    ],
    road: [2, 4, 15],
    city_name: 'Izanami',
    desc: 'Izanami şehri, mistik bir atmosfere sahip ve bu savaşta iki klan arasındaki güç dengesi oldukça farklı.',
  },
  {
    war_id: 0,
    id: 4,
    clan: 0,
    attackersPower: 42,
    defendersPower: 39,
    value: 6,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['kaito', 13, '0x000f'],
      ['satoshi', 15, '0x000f'],
      ['yuta', 14, '0x000f'],
    ],
    defenderSamurai: [
      ['takashi', 12, '0x000f'],
      ['kazuya', 18, '0x000f'],
      ['yusuke', 9, '0x000f'],
    ],
    road: [5, 2, 3, 15, 14],
    city_name: 'Sapporo',
    desc: "Sapporo, Japonya'nın kuzeyinde yer alan ve her yıl düzenlenen kış festivaliyle ünlü olan bir şehirdir. Bu savaş, Sapporo'nun göl kenarındaki parkında gerçekleşiyor.",
  },
  {
    war_id: 0,
    id: 5,
    clan: 0,
    attackersPower: 50,
    defendersPower: 44,
    value: 8,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['akio', 20, '0x000f'],
      ['haru', 18, '0x000f'],
      ['shinji', 12, '0x000f'],
    ],
    defenderSamurai: [
      ['ayumi', 13, '0x000f'],
      ['naoki', 20, '0x000f'],
      ['yuki', 11, '0x000f'],
    ],
    road: [2, 4],
    city_name: 'Kanazawa',
    desc: "Kanazawa, Japonya'nın merkezinde yer alan ve tarihi binaları, bahçeleri ve müzeleriyle ünlü olan bir şehirdir. Bu savaş, şehir merkezindeki bir kalesinde gerçekleşiyor.",
  },
  {
    war_id: 0,
    id: 6,
    clan: 0,
    attackersPower: 50,
    defendersPower: 45,
    value: 6,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['yusuf', 18, '0x000f'],
      ['baran', 16, '0x000f'],
      ['emre', 16, '0x000f'],
    ],
    defenderSamurai: [
      ['aslı', 14, '0x000f'],
      ['cengiz', 15, '0x000f'],
      ['kemal', 16, '0x000f'],
    ],
    road: [],
    city_name: 'Kobe',
    desc: "Kobe, Japonya'nın Honshu adasında yer alan bir liman kenti. Kobe'nin güzel bahçeleri ve tatlı su kaynakları ile ünlüdür.",
  },
  {
    war_id: 0,
    id: 7,
    clan: 0,
    attackersPower: 58,
    defendersPower: 60,
    value: 8,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['Eren', 25, '0x000f'],
      ['Onur', 20, '0x000f'],
      ['Burak', 13, '0x000f'],
    ],
    defenderSamurai: [
      ['Sena', 19, '0x000f'],
      ['Alper', 18, '0x000f'],
      ['Ege', 23, '0x000f'],
    ],
    road: [8, 9],
    city_name: 'Sapporo',
    desc: "Sapporo, Hokkaido Adası'nın güneybatısında yer alan Japonya'nın beşinci büyük şehridir. Sapporo'nun en ünlü olayı kış festivalidir.",
  },
  {
    war_id: 0,
    id: 8,
    clan: 0,
    attackersPower: 42,
    defendersPower: 45,
    value: 6,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['Takao', 14, '0x000f'],
      ['Yoshida', 16, '0x000f'],
      ['Nakamura', 12, '0x000f'],
    ],
    defenderSamurai: [
      ['Saito', 12, '0x000f'],
      ['Miyamoto', 18, '0x000f'],
      ['Kato', 15, '0x000f'],
    ],
    road: [24, 7, 9, 10],
    city_name: 'Hiroshima',
    desc: "Hiroshima, Japonya'nın güneybatısındaki Honshu adasında bulunan bir şehirdir. Bu savaşta iki klan arasındaki güç dengesi oldukça yakındır.",
  },
  {
    war_id: 0,
    id: 9,
    clan: 0,
    attackersPower: 48,
    defendersPower: 50,
    value: 8,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['Daiki', 16, '0x000f'],
      ['Kenta', 19, '0x000f'],
      ['Yusuke', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['Miki', 10, '0x000f'],
      ['Kazuhiro', 16, '0x000f'],
      ['Arisa', 24, '0x000f'],
    ],
    road: [7, 8, 10, 11, 12],
    city_name: 'Kumamoto',
    desc: "Kumamoto, Japonya'nın Kyushu adasında yer alan bir şehirdir. Bu savaşta iki klan arasında oldukça yüksek bir meblağ bahis oynanmaktadır.",
  },
  {
    war_id: 0,
    id: 10,
    clan: 0,
    attackersPower: 55,
    defendersPower: 58,
    value: 10,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['mustafa', 16, '0x000f'],
      ['batuhan', 19, '0x000f'],
      ['mehmet', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['aylin', 10, '0x000f'],
      ['tuna', 16, '0x000f'],
      ['berk', 24, '0x000f'],
    ],
    road: [8, 9, 11],
    city_name: 'Kagutsuchi',
    desc: 'Kagutsuchi şehri, kutsal bir volkanın eteklerinde yer alıyor ve bu savaşta iki klan arasında oldukça yüksek bir meblağ bahis oynanıyor.',
  },
  {
    war_id: 0,
    id: 11,
    clan: 0,
    attackersPower: 42,
    defendersPower: 36,
    value: 6,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['kaito', 18, '0x000f'],
      ['yuki', 12, '0x000f'],
      ['ayumi', 12, '0x000f'],
    ],
    defenderSamurai: [
      ['sakura', 16, '0x000f'],
      ['seiichi', 10, '0x000f'],
      ['kaori', 10, '0x000f'],
    ],
    road: [9, 10, 12, 20, 21],
    city_name: 'Kanagawa',
    desc: "Kanagawa şehri, Japonya'nın en kalabalık bölgelerinden biridir ve geleneksel ve modern kültürleri harmanlar. Bu savaşta iki klan arasındaki güç dengesi oldukça yakın.",
  },
  {
    war_id: 0,
    id: 12,
    clan: 0,
    attackersPower: 41,
    defendersPower: 37,
    value: 3,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['toshiro', 10, '0x000f'],
      ['akio', 14, '0x000f'],
      ['yukio', 17, '0x000f'],
    ],
    defenderSamurai: [
      ['sakura', 8, '0x000f'],
      ['kenji', 13, '0x000f'],
      ['haru', 16, '0x000f'],
    ],
    road: [9, 11, 20, 19, 13],
    city_name: 'Mito',
    desc: 'Mito şehri, doğal güzellikleri ve kültürel zenginlikleriyle ünlüdür. Ancak bu savaşta, iki klan arasındaki güç dengesi oldukça yakın.',
  },
  {
    war_id: 0,
    id: 13,
    clan: 0,
    attackersPower: 53,
    defendersPower: 46,
    value: 6,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['hayato', 18, '0x000f'],
      ['nagato', 19, '0x000f'],
      ['takao', 16, '0x000f'],
    ],
    defenderSamurai: [
      ['aya', 15, '0x000f'],
      ['yoko', 17, '0x000f'],
      ['akira', 14, '0x000f'],
    ],
    road: [12, 19, 18, 14],
    city_name: 'Hiratsuka',
    desc: 'Hiratsuka şehri, geleneksel festivalleri ve modern sanatıyla ünlüdür. Bu savaşta ise iki klan arasındaki güç dengesi oldukça dengesiz görünüyor.',
  },
  {
    war_id: 0,
    id: 14,
    clan: 0,
    attackersPower: 62,
    defendersPower: 54,
    value: 9,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['shiro', 23, '0x000f'],
      ['ren', 20, '0x000f'],
      ['sora', 19, '0x000f'],
    ],
    defenderSamurai: [
      ['yuri', 17, '0x000f'],
      ['mio', 18, '0x000f'],
      ['kaori', 19, '0x000f'],
    ],
    road: [4, 15, 17, 18, 13],
    city_name: 'Nagareyama',
    desc: 'Nagareyama şehri, tarihi anıtları ve doğal güzellikleriyle',
  },
  {
    war_id: 0,
    id: 15,
    clan: 0,
    attackersPower: 48,
    defendersPower: 54,
    value: 8,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['Ryu', 16, '0x000f'],
      ['Haru', 16, '0x000f'],
      ['Kenji', 16, '0x000f'],
    ],
    defenderSamurai: [
      ['Aki', 18, '0x000f'],
      ['Taro', 18, '0x000f'],
      ['Mari', 18, '0x000f'],
    ],
    road: [3, 4, 14, 17, 16],
    city_name: 'Mito',
    desc: "Mito şehri Japonya'nın Kanto bölgesinde yer alır ve bu savaşta iki klan arasında yüksek bir bahis oynanmaktadır.",
  },
  {
    war_id: 0,
    id: 16,
    clan: 0,
    attackersPower: 60,
    defendersPower: 56,
    value: 9,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['Sora', 20, '0x000f'],
      ['Jin', 20, '0x000f'],
      ['Hana', 20, '0x000f'],
    ],
    defenderSamurai: [
      ['Shiro', 18, '0x000f'],
      ['Kana', 20, '0x000f'],
      ['Kaito', 18, '0x000f'],
    ],
    road: [15, 17, 23],
    city_name: 'Takamatsu',
    desc: "Takamatsu şehri, Japonya'nın Shikoku adasında yer alır ve bu savaşta iki klan arasındaki güç dengesi oldukça yakındır.",
  },
  {
    war_id: 0,
    id: 17,
    clan: 0,
    attackersPower: 65,
    defendersPower: 60,
    value: 20,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['kaito', 25, '0x000f'],
      ['yumi', 20, '0x000f'],
      ['haru', 20, '0x000f'],
    ],
    defenderSamurai: [
      ['makoto', 30, '0x000f'],
      ['akio', 20, '0x000f'],
      ['chiaki', 10, '0x000f'],
    ],
    road: [14, 15, 16, 23, 24, 18],
    city_name: 'Tachikawa',
    desc: 'Tachikawa şehri, modern bir şehir olmasına rağmen tarihi dokusunu koruyan bir yer. Bu savaşta iki klan arasındaki güç dengesi oldukça yakın.',
  },
  {
    war_id: 0,
    id: 18,
    clan: 0,
    attackersPower: 75,
    defendersPower: 70,
    value: 25,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['tatsuya', 30, '0x000f'],
      ['ayumu', 25, '0x000f'],
      ['shota', 20, '0x000f'],
    ],
    defenderSamurai: [
      ['naoko', 35, '0x000f'],
      ['tomoe', 20, '0x000f'],
      ['yukari', 15, '0x000f'],
    ],
    road: [14, 17, 24, 19, 13],
    city_name: 'Takarazuka',
    desc: 'Takarazuka şehri, ünlü Takarazuka Revue tiyatrosunun bulunduğu bir yer. Bu savaşta iki klan arasındaki güç dengesi oldukça yakın.',
  },
  {
    war_id: 0,
    id: 19,
    clan: 0,
    attackersPower: 85,
    defendersPower: 90,
    value: 30,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['ren', 35, '0x000f'],
      ['ayaka', 25, '0x000f'],
      ['haruka', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['hiroshi', 40, '0x000f'],
      ['yuko', 25, '0x000f'],
      ['akemi', 20, '0x000f'],
    ],
    road: [12, 13, 18, 20, 25],
    city_name: 'Shizuoka',
    desc: "Shizuoka şehri, Fuji Dağı'nın eteklerinde yer alan bir şehir. Bu savaşta savunma tarafındaki klan biraz daha güçlü görünüyor.",
  },
  {
    war_id: 0,
    id: 20,
    clan: 0,
    attackersPower: 70,
    defendersPower: 75,
    value: 25,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['kazuo', 30, '0x000f'],
      ['mika', 20, '0x000f'],
      ['aya', 20, '0x000f'],
    ],
    defenderSamurai: [
      ['toshiro', 40, '0x000f'],
      ['yusuke', 20, '0x000f'],
      ['naomi', 15, '0x000f'],
    ],
    road: [11, 12, 19, 25, 22, 21],
    city_name: 'Kawasaki',
    desc: "Kawasaki şehri, Tokyo'nun hemen batısında yer alan büyük bir liman şehri. Bu savaşta savunma gücü biraz daha üstün.",
  },
  {
    war_id: 0,
    id: 21,
    clan: 0,
    attackersPower: 90,
    defendersPower: 85,
    value: 30,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['natsuki', 35, '0x000f'],
      ['satomi', 30, '0x000f'],
      ['ren', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['sakura', 40, '0x000f'],
      ['akira', 20, '0x000f'],
      ['yuto', 15, '0x000f'],
    ],
    road: [11, 20, 22],
    city_name: 'Kashiwa',
    desc: 'Kashiwa şehri, Chiba eyaletinde bulunan önemli bir ticaret merkezi. Bu savaşta saldırgan güç biraz daha üstün.',
  },
  {
    war_id: 0,
    id: 22,
    clan: 0,
    attackersPower: 80,
    defendersPower: 75,
    value: 25,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['yui', 30, '0x000f'],
      ['haruka', 25, '0x000f'],
      ['kei', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['kenta', 35, '0x000f'],
      ['yuto', 20, '0x000f'],
      ['ayumi', 20, '0x000f'],
    ],
    road: [21, 20, 25],
    city_name: 'Machida',
    desc: "Machida şehri, Tokyo'nun güneybatısında yer alan bir banliyö şehri. Bu savaşta saldırgan güç biraz daha üstün.",
  },
  {
    war_id: 0,
    id: 23,
    clan: 0,
    attackersPower: 95,
    defendersPower: 80,
    value: 35,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['kazuki', 40, '0x000f'],
      ['takashi', 30, '0x000f'],
      ['hikaru', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['yoshiko', 35, '0x000f'],
      ['sakura', 30, '0x000f'],
      ['kana', 15, '0x000f'],
    ],
    road: [16, 17, 24],
    city_name: 'Matsue',
    desc: "Matsue şehri, Japonya'nın tarihi kentlerinden biri ve birçok tarihi esere ev sahipliği yapıyor. Bu savaşta ise iki klan arasındaki güç dengesi oldukça yakın.",
  },
  {
    war_id: 0,
    id: 24,
    clan: 2,
    attackersPower: 105,
    defendersPower: 90,
    value: 40,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['tsubasa', 45, '0x000f'],
      ['akira', 35, '0x000f'],
      ['haruto', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['hiroko', 40, '0x000f'],
      ['miho', 30, '0x000f'],
      ['kumiko', 20, '0x000f'],
    ],
    road: [8],
    city_name: 'Suku',
    desc: "Suku şehri, Mie Prefektörlüğü'nün başkenti ve birçok tarihi anıta ev sahipliği yapıyor. Bu savaşta ise iki klan arasındaki güç dengesi oldukça yakın.",
  },
  {
    war_id: 0,
    id: 25,
    clan: 0,
    attackersPower: 105,
    defendersPower: 90,
    value: 40,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['tsubasa', 45, '0x000f'],
      ['akira', 35, '0x000f'],
      ['haruto', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['hiroko', 40, '0x000f'],
      ['miho', 30, '0x000f'],
      ['kumiko', 20, '0x000f'],
    ],
    road: [],
    city_name: 'Tsu',
    desc: "Tsu şehri, Mie Prefektörlüğü'nün başkenti ve birçok tarihi anıta ev sahipliği yapıyor. Bu savaşta ise iki klan arasındaki güç dengesi oldukça yakın.",
  },
  {
    war_id: 0,
    id: 26,
    clan: 0,
    attackersPower: 105,
    defendersPower: 90,
    value: 40,
    attackerClan: 0,
    defenderClan: 0,
    attackerSamurai: [
      ['tsubasa', 45, '0x000f'],
      ['akira', 35, '0x000f'],
      ['haruto', 25, '0x000f'],
    ],
    defenderSamurai: [
      ['hiroko', 40, '0x000f'],
      ['miho', 30, '0x000f'],
      ['kumiko', 20, '0x000f'],
    ],
    road: [17, 18, 23],
    city_name: 'Tsu',
    desc: "Tsu şehri, Mie Prefektörlüğü'nün başkenti ve birçok tarihi anıta ev sahipliği yapıyor. Bu savaşta ise iki klan arasındaki güç dengesi oldukça yakın.",
  },
];
